---
- name: Install onapp-cp-install
  yum:
    name: onapp-cp-install
    state: latest

- name: Check whether OnApp is installed
  stat:
    path: /onapp/interface/config/on_app.yml
  register: onapp_installed

- name: Install CP
  command: /onapp/onapp-cp-install/onapp-cp-install.sh -v {{ onapp_package }} -a
  when: not onapp_installed.stat.exists

- name: Add PassengerStartTimeout
  lineinfile:
    path: /etc/httpd/conf.d/onapp.conf
    line: "PassengerStartTimeout 600"

- name: Reload Apache
  systemd:
    name: httpd
    state: reloaded
